name: Publish RouteAPI NuGet (Prod)

on:
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

    - name: Restore dependencies
      run: dotnet restore ./RouteAPI/Library/RouteAPI.csproj
      
    - name: Pack
      run: |
        dotnet pack ./RouteAPI/Library/RouteAPI.csproj -c Release -o ./dist --no-restore

    - name: Push to NuGet
      run: dotnet nuget push ./dist/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json


  build-debug:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

    - name: Restore dependencies
      run: dotnet restore ./RouteAPI/Library/RouteAPI.csproj
      
    - name: Pack
      run: |
        dotnet pack ./RouteAPI/Library/RouteAPI.csproj -c Debug -o ./dist --no-restore

    - name: Push to NuGet
      run: dotnet nuget push ./dist/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json